version: '3'

services:
  db:
    image: mariadb:latest
    container_name: site2_db
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=site2_db
    expose:
      - 3306
    volumes:
      - ./db/data:/var/lib/mysql
      - ./db/sql:/mnt/files/sql

  phpfpm:
    build:
      context: ./docker/php
      dockerfile: Dockerfile
    container_name: site2_phpfpm
    restart: always
    expose:
      - 9000
    volumes:
      - ./src/:/var/www/html
    depends_on:
      - db

  web:
    build:
      context: ./docker/nginx
      dockerfile: Dockerfile
    container_name: site2_web
    restart: unless-stopped
    environment:
      - VIRTUAL_HOST=www.site2.local
      - LETSENCRYPT_HOST=www.site2.local
    expose:
      - 80
      - 443
    working_dir: /var/www/html
    volumes:
      - ./src:/var/www/html
    depends_on:
      - phpfpm

  phpmyadmin:
    image: phpmyadmin
    container_name: site2_phpmyadmin
    restart: always
    expose:
      - 80
    environment:
      - PMA_HOST=db
      - PMA_PORT=3306
      - PMA_ARBITRARY=1
      - MYSQL_ROOT_PASSWORD=root
      - VIRTUAL_HOST=myadmin.site2.local
      - LETSENCRYPT_HOST=myadmin.site2.local
    depends_on:
      - db


networks:
  default:
    external:
      name: nginx-proxy